### ISSUE TITLE
درخواست ترکیب با سایر قلم‌ها

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-code-font#1]
اگرچه ایجاد ترکیب‌های متفاوت برای سلایق گوناگون از توان من خارج هست اما اینجا میتونه محلی باشه برای جمع‌آوری درخواست‌ها و سلایق متفاوت در زمینه قلم کدنویسی و البته بیشترین گرایش!

شما دوست می‌دارید وزیرکد با چه قلم (هایی) ترکیب شود؟
در صورتی که تصویری هم از قلم مورد نظرتان بگذارید که خیلی خوب می شود.

با تشکر

**Comment by aziz** [comment]
اینم چند تا گزینه

|       Font      |  Company  |        License         |
|-----------------|-----------|------------------------|
| fira-mono       | Mozila    | SIL OFL 1.1            |
| roboto-mono     | Google    | Apache 2.0             |
| source-code-pro | Adobe     | SIL OFL 1.1            |
| ubuntu-mono     | Canonical | Ubuntu Font License    |
| Inconsolata     |           | SIL OFL 1.1            |
| hack            |           | Hack Open Font License |
| mononoki        |           | SIL OFL 1.1            |

**Comment by mhbashari** [comment]
Salam
Zemne tashakkor az in kare arzeshmand.

---> **Consolas**

**Comment by aziz** [comment]
**Consolas** is not an open source font. We're not allowed to change it.

**Comment by hamidazimy** [comment]
‫فونت Inconsolata بسیار فونت خوبیه و خیلی خیلی خوشحال شدم که فونت شما با این فونت ترکیب شده، نتیجه واقعاً عالیه.
‫فقط این فونت یه ایراد کوچیک داره که اتفاقاً خود سازنده توی یه نسخه دیگه از فونت به اسم InconsolataGo حلش کرده
‫و اون مشکل هم اینه که کوتیشن‌ها (single quotation و double quotation) صاف نیستن و مورب هستن
[http://levien.com/type/myfonts/inconsolata.html](http://levien.com/type/myfonts/inconsolata.html)
‫(انتهای پاراگراف اول لینک فونت اصلاح شده هست)
این هم عکسش
[http://uploads.im/zSoMg.png](http://uploads.im/zSoMg.png)
‫پیشنهاد من اینه که شما هم این تغییر رو اعمال کنید و یا فونت پیش‌فرض رو روی InconsolataGo بذارید که این مشکل کوچیک هم رفع بشه
باز هم خیلی خیلی ممنونم از تلاش ارزشمندتون برای تهیه این فونت و بقیه فونت‌ها. کارتون واقعاً عالیه

**Comment by hamidazimy** [comment]
‫با تشکر فراوان بابت این که کامنتم رو اعمال کردید. واقعاً عالی شد نتیجه
‫یه پیشنهاد دیگه هم داشتم، اونم اینه که یه نسخه خام از فونت هم بذارید، یعنی با Inconsolata یا هیچ فونت دیگه‌ای ترکیب نشده باشه.
‫فکر می‌کنم اینجوری راحت‌تره باشه اگه کسی بخواد از فونت دیگه‌ای در کنارش استفاده کنه.
باز هم خیلی خیلی ممنون

**Comment by rastikerdar** [comment]
@hamidazimy اولا از شما برای گزارش این موضوع و توضیحات خوبتون تشکر می کنم. باز هم اگر موردی مشاهده فرمودید ممنون میشم در جریان بگذارید.

اما در مورد نسخه خامی که فرمودید مشکل اینجاست که اندازه طولی حروف قلم اینکانسولاتو با بقیه یکسان نیست. یعنی بقیه روی ۶۰۰ واحد (یا ضریب دو آن) ساخته شده اند اما اینکانسولاتا روی ۵۰۰ واحد! برای همین استفاده از وزیرکد خام کنار بقیه باعث تداخل این قابلیت مونواسپیس بودنش میشه. مگر اینکه یه نسخه ۶۰۰ واحدی هم از وزیرکد ایجاد بشه که به راحتی با بقیه ترکیب بشه.

**Comment by rastikerdar** [comment]
600  fira-mono
600  fira-mono
600  fira-mono
600  fira-mono

**Comment by rastikerdar** [comment]
600  fira-mono
600  source-code-pro
500  ubuntu-mono
500  Inconsolata
600  hack
575  mononoki
600  roboto-mono

اندازه ها یکسان نیست متاسفانه.

نکته: گیتهاب با
ctrl+enter
پیام شما رو پست میکنه! من اشتباهی قبلی رو پست کردم.

**Comment by hamidazimy** [comment]
@rastikerdar خواهش می‌کنم، حتماً اگر موردی به ذهنم رسید مطرح می‌کنم. باز هم ممنون از شما

‫آها! واقعیتش من با چالش‌های فنی این کار چندان آشنایی ندارم و نمی‌دونستم که به این راحتی نیست! :smile: 
‫برای این که راحتتر بشه از فونت‌های دیگه در کنار وزیر کد استفاده کرد این پیشنهاد رو دادم.
‫ولی خب من که شخصاً با از ترکیب با Inconsolata بسیار راضی‌ام!
‫(هر چند بدم نمیاد یه سری تغییرات سلیقه‌ای توی Inconsolata بدم :grey_exclamation: )

**Comment by Qaher-Marufiazar** [comment]
پیشنهاد من اول رلیز نسخه‌ی بی ایراد وزیر کد با همین فونت اولیه هستش و سپس حتما با یک فونت خوب دیگه‌ای که غالبا بهتر و سنگین‌وزن‌تره هم ترکیب بشه؛ تحت عنوان مجزایی (مثلا وزیر کد با فونت لاتین هک). پیشنهاد من استفاده از این فونت‌های لاتین بجای فونت پیشفرض فعلی وزیر کد نسخه‌ی 1.0.3 هستش جدای از بحث رایگان بودن یا نبودن فونت‌ها:

به ترتیب اولیت و بهتر بودن از بالا به پایین، من شخصا این فونت‌ها رو برای بخش لاتین ترجیح میدم:

| Consolas  | 
| ------------- | 
| Droid Sans Mono  | 
| Hack  |
| Monaco |

**Comment by OxusT** [comment]
لطفاً از قلم کُنسولاس (نام انگلیسی در پایین پیام) استفاده کنید چرا که قلم پیش‌فرض در دو تا از پراستفاده‌ترین نرم‌افزار‌های برنامه‌نویسی‌ است. (ویژوال استودیو و ویژوال استودیو کد، منبع پایین)

Consolas

https://insights.stackoverflow.com/survey/2019

**Comment by OxusT** [comment]
> اگرچه ایجاد ترکیب‌های متفاوت برای سلایق گوناگون از توان من خارج هست اما اینجا میتونه محلی باشه برای جمع‌آوری درخواست‌ها و سلایق متفاوت در زمینه قلم کدنویسی و البته بیشترین گرایش!
> 
> شما دوست می‌دارید وزیرکد با چه قلم (هایی) ترکیب شود؟
> در صورتی که تصویری هم از قلم مورد نظرتان بگذارید که خیلی خوب می شود.
> 
> با تشکر

لطفاً از قلم کُنسولاس (نام انگلیسی در پایین پیام) استفاده کنید چرا که قلم پیش‌فرض در دو تا از پراستفاده‌ترین نرم‌افزار‌های برنامه‌نویسی‌ است. (ویژوال استودیو و ویژوال استودیو کد، منبع پایین)

Consolas

https://insights.stackoverflow.com/survey/2019

**Comment by SepSol** [comment]
اول از همه میخواستم از خدمتتون بابت فونت‌های بسیار بسیار عالی و خوبتون تشکر کنم، به نظرم ترکیب وزیرکد با فونت‌های اوپن سورس [Fira Code](https://github.com/tonsky/FiraCode) و [Fira Code iScript](https://github.com/kencrocken/FiraCodeiScript) میتونه جالب بشه،
.
.
.
### Fira Code:
[![image](https://user-images.githubusercontent.com/47871887/75954177-5756d500-5ec8-11ea-9424-92239366ffd2.png)](https://github.com/tonsky/FiraCode)
.
.
### Fira Code iScript:
[![image](https://user-images.githubusercontent.com/47871887/75954197-60e03d00-5ec8-11ea-9b02-dc6266882ef4.png)](https://github.com/kencrocken/FiraCodeiScript)
.
.
.
چون این فونت‌ها از ligature های مخصوص برنامه‌نویسی پشتیبانی می‌کنن ولی فونت فارسی‌شون قشنگ نیست. همینطور اگه درمورد فونت دومی بتونید قلم دست‌نویس به وزیرکد اضافه کنید که در کنار قلم دست‌نویس [Fira Code iScript](https://github.com/kencrocken/FiraCodeiScript) در کامنت‌ها دیده بشن عالی میشه.

**Comment by Azoic** [comment]
سلام
لطفا فونت jetbrains mono هم بررسی کنید

https://github.com/JetBrains/JetBrainsMono

**Comment by Monirzadeh** [comment]
لطفا در صورت امکان نسخه‌ای با ترکیب با ubuntu-mono منتشر نمایید

**Comment by Monirzadeh** [comment]
لطفا نسخه‌ای همراه با mono space نیز منتشر کنید

**Comment by rasa-app** [comment]
با سلام و تشکر از زحمات شما در صورت امکان حروف فارسی را با فونت 
JetBrains Mono
ترکیب کنید
[https://www.jetbrains.com/lp/mono/](url)

با تشکر

**Comment by AradAral** [comment]
با عرض سلام و خسته نباشید. ممنون بابت این پروژه‌ی فوق‌العاده.
منم درخواست دارم اگر ممکنه با فونت
Fira Code
ترکیب بشه.
شخصاً از این فونت استفاده می‌کنم، اما متأسفانه اندازه‌ها یکسان نیست.
![image](https://user-images.githubusercontent.com/26527405/139598841-13a473ab-b442-4238-9b52-7b06a88d53d2.png)

**Comment by matinmn87** [comment]
سلام و تشکر فراوان از شما.
https://github.com/microsoft/cascadia-code/
در صورت امکان فونت را با Cascadia Code ترکیب کنید.

**Comment by aaaamirabbas** [comment]
سلام آقا یه نفره کل نیاز فونت کشور رو تامین کردی واقعا ممنونم ازت 👍 
لطفا فونت ubuntu mono رو هم اضافه کن و همچنین inconsolata طی این سال ها آپدیت شده و شما هم آپدیت کن و نسخه متغیر رو هم اضافه کن در کنار نسخه های استاتیک

خیلی ممنون که لطف میکنی.

**Comment by aaaamirabbas** [comment]
البته لازمه بگم الان ادیتور ها از چند فونت پشتیبانی میکنن و میشه از وزیرمتن و فونت های mono به صورت **مرکب** استفاده کرد برای مثال:

در vscode وقتی فونت دوم روی وزیرمتن تنظیم بشه به صورت خودکار برای حروف لاتین از فونت مونو (هر فونتی) و برای حروف فارسی از وزیر متن استفاده میشه

این مورد رو من در intellij idea و بقیه هم تست گرفتم و به نظر میرسه برای همه ادیتور ها قابل تنظیم باشه

**ظاهرا وقتی حروف فارسی رو در فونت اول پیدا نمیکنه, این حروف رو از فونت دوم میگیره و این خیلی عالیه**

**Comment by matinmn87** [comment]
> البته لازمه بگم الان ادیتور ها از چند فونت پشتیبانی میکنن و میشه از وزیرمتن و فونت های mono به صورت **مرکب** استفاده کرد برای مثال:
> 
> در vscode وقتی فونت دوم روی وزیرمتن تنظیم بشه به صورت خودکار برای حروف لاتین از فونت مونو (هر فونتی) و برای حروف فارسی از وزیر متن استفاده میشه
> 
> این مورد رو من در intellij idea و بقیه هم تست گرفتم و به نظر میرسه برای همه ادیتور ها قابل تنظیم باشه
> 
> **ظاهرا وقتی حروف فارسی رو در فونت اول پیدا نمیکنه, این حروف رو از فونت دوم میگیره و این خیلی عالیه**

سلام. برای ویژوال استودیو هم این فیچر هست؟ اگه هست می‌شه لطفا بگین کجا هست؟
با تشکر
