### ISSUE TITLE
فقدان کاراکترهای لاتین

### ISSUE THREAD

**Issue by hafezdivandari** [rastikerdar/vazir-code-font#10]
سلام، تعداد زیادی از کاراکترهای لاتین موجود در فونت
`Inconsolata`
در فونت وزیر کد وجود ندارد مثل این ها:
Ā : U+0100
ā : U+0101
و...
راهی برای افزودن این کاراکترها هست؟

**Comment by rastikerdar** [comment]
در نسخه بعدی با نسخه جدید فونت لاتین هماهنگ خواهدشد. ممنونم برای گزارش این ایراد.

**Comment by rastikerdar** [comment]
در نسخه جدید تمامی گلیف‌های فونت‌های لاتین قرار گرفت.
Inconsolata و Hack
[rastikerdar.github.io/vazir-code-font/](https://rastikerdar.github.io/vazir-code-font/)
با تشکر
