### ISSUE TITLE
کاراکتر ZWNJ در فونت Monospace بدون عرض است

### ISSUE THREAD

**Issue by sadeqn** [rastikerdar/vazir-code-font#12]
‫بنظر می‌رسد با توجه به کاربرد Monospaceها لازم است کاراکتر zwnj هم دارای عرض مساوی با بقیه کاراکترها داشته باشد. مثلا در هنگام نوشتن متن و تهیه جدول در متنی مثلا با فرمت MD یا مانند آن استفاده از کاراکتر ZWNJ باعث به هم ریختن نمایش جدول می‌شود.

**Comment by aziz** [comment]
Zero-width non-joiner
باید عرضش صفر باشد.
کما اینکه در تستی که من انجام دادم صفر است. احتمالا مشکل از ویرایشگری است که استفاده می‌کنید و نه این قلم

<img width="171" alt="screen shot 2017-08-26 at 12 38 21 pm" src="https://user-images.githubusercontent.com/3202/29740644-9a32bb62-8a5b-11e7-8f44-747c680fc9dd.png">

**Comment by rastikerdar** [comment]
@aziz 
 فکر می‌کنم منظور آقا صادق اینه که نباید صفر باشه. چون عرض همه گلیف‌ها باید یکسان باشه تا فونت کاملا مونواسپیس باشه.

@sadeqn 
خب راستش من طبق همین چیزی که عزیز فرمودند عمل کردم. در واقع نگاه کردم به بقیه فونت‌های مونو عربی دیدم اونها هم عرضش رو صفر در نظر گرفته‌اند. یعنی نمی‌دونم چه باید کرد چون ایرادی که می‌فرمایید میتونه مشکل ساز باشه. از اون طرف اگر هم بخواهیم اصلاحش کنیم نباید با فاصله معمولی اشتباه گرفته بشه و به نوعی باید دارای علامت خاصی باشه.
نکته: در مورد اعراب هم این مشکل وجود داره.

**Comment by zoghal** [comment]
خصوصیات سیستمی در اعراب و فاصله کوتاه و کاراکتر‌های کنترلر در یونیکد همانند سایر حروف نیستند. و این مورد رو باید ادیتور مورد استفاده یا موتور نمایشگر رعایت کند!

@sadeqn  ایا امکان دارد یک نمونه تست  قرار بدید و بگید در چه ادیتوری و سیستم عاملی این مشکل رو دید؟

**Comment by Qaher-Marufiazar** [comment]
سلام. عرض یونیکد مربوط به نیم‌فاصله الزاما باید صفر بشه. نه فقط به خاطر اینکه اسمشم به همین معنی هستش بلکه صفر شدنش هیچ خللی در مونواسپیس بودن فونت ایجاد نمیکنه! مثل اینه که یک کاراکتری که عرضش با بقیه یکی هستش قرار نیست تایپ بشه.

**Comment by rastikerdar** [comment]
من اصلا حواسم نبود که نیم فاصله توی ورژن آخر ۵۰۰ شده. احتمالا حواسم نبوده همه رو یکی کردم. خب حالا که عرضش با بقیه یکسان شده یا برگردونیم به صفر یا با یک علامت متمایزش کنیم تا با فاصله اشتباه نشه.

پیشنهاد شما چیه؟
به صفر برگرده؟

**Comment by Qaher-Marufiazar** [comment]
حالا صفر شدن عرض این کاراکتر که الزامیه یکی دو تا کاراکتر دیگه هم هستش که ظاهرا اشتباهی اونا هم عرضشون 500 شده! مثل جوینر همین کاراکتر.
Zero Width Joiner (ZWJ)

**Comment by rastikerdar** [comment]
در نسخه جدید مشکل برطرف گردید
با تشکر
