### ISSUE TITLE
نسخه بدون لاتین

### ISSUE THREAD

**Issue by morealaz** [rastikerdar/vazir-code-font#13]
<div dir="rtl">
اگر امکانش وجود داشته که نسخه بدون لاتین هم داشته باشیم، میشه از فونت لاتین دلخواه استفاده کرد. البته در #1 شما فرمودید که بدلیل تفاوت سایز فونتهای مختلف این امکان وجود نداره. ولی آیا میشه چند سایز از فونت رو داشته باشیم؟ مثل فونت وزیر که مثلا نسخه های نازک و متوسط رو داره.

**Comment by rastikerdar** [comment]
من سعی می‌کنم فارسی رو از لاتین جدا کنم تا حتی اگه فرصت کنم توی بسته دانلود ترکیبش رو با چند تا فونت دیگه هم بزارم.
در مورد سایزهای مختلف شدنی که میشه ولی خب زحمت داره.

**Comment by rastikerdar** [comment]
دو نسخه سورس بدون لاتین با دو سایز متداول قرار داده شد.
Inconsolata و Hack
با تشکر

**Comment by morealaz** [comment]
با تشکر
منظور من از بدون لاتین چیزی مثل فونت
`Vazir WOL`
بود که بشه با استفاده از تنظیمات 
`fontconfig` 
کاری کرد که برای حروف فارسی از فونت وزیر استفاده بشه و برای حروف لاتین و غیره از فونت دلخواه دیگه استفاده بشه.
آیا نسخه جدید به همین صورت هست؟

**Comment by rastikerdar** [comment]
نسخه بدون لاتین هم به بخش فایل‌ها اضافه کردم که در لینک زیر قابل دریافت است
[github.com/rastikerdar/vazir-code-font/releases/tag/v1.1.0](https://github.com/rastikerdar/vazir-code-font/releases/tag/v1.1.0)

**Comment by morealaz** [comment]
بسیار عالی
ممنون از لطف شما

**Comment by morealaz** [comment]
اگر کسی خواست فونت های پیش فرض سیستم رو در لینوکس تنظیم کنه و از فونت وزیر و وزیر کد برای فونت پیش 
فرض سیستم استفاده کنه میتونه به صورت زیر عمل کند
محتویات فایل 
`/etc/fonts/local.conf`
رو به صورت زیر قرار بدهید

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Serif</family>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Vazir WOL</family>
      <family>Noto Sans</family>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Vazir Code Hack WOL</family>
      <family>Hack</family>
      <family>Noto Sans Mono</family>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
کافیست زیر بخش مربوط به خانواده های مختلف فونت، فونت های دلخواه خودتون رو به ترتیب اولویت قرار دهید البته با توجه به این نکته که نسخه های بدون لاتین فونت وزیر و وزیر کد حتما به عنوان اولویت اول قرار بگیرد

**Comment by morealaz** [comment]
با سلام و تشکر
اگر امکانش هست نسخه بدون لاتین رو برای نسخه های جدید هم منتشر کنید.

**Comment by rastikerdar** [comment]
با سلام و سپاس
توی صفحه انتشار قرار داده شد. البته فکر می‌کنم این هم مثل بقیه فونت‌ها باید همه حالت‌های مختلف رو توی خود بسته اصلی داشته باشه اما چون احساس می‌کردم شلوغ و سنگین میشه و احتمالا کسی نیاز پیدا نکنه حذفشون می‌کردم. شاید اشتباه می‌کردم.
[vazir-code-font/releases](https://github.com/rastikerdar/vazir-code-font/releases)

**Comment by morealaz** [comment]
شما برای این فونت در دو نسخه مختلف از دو فونت لاتین مختلف استفاده کردید برای سلایق مختلف
ولی ممکن هست کسی بخواهد از یک فونت دیگه برای فونت لاتین استفاده کنه که اینجا نسخه بدون لاتین خیلی بدرد می خوره و نیاز نیست برای هر فونت لاتین یه نسخه جداگانه منتشر بشه
باز هم از زحمات شما تشکر میکنم و خواهش میکنم برای این فونت هم مثل فونت وزیر تمام حالت های مختلف رو در یک بسته قرار بدهید.

**Comment by rastikerdar** [comment]
از نسخه آتی طبق فرمایش شما منتشر خواهد شد. البته این نکته رو هم در نظر داشته باشید که برای ترکیب با سایر فونت‌های لاتین، عرض و سایز هر دو باید یکی باشد.
