### ISSUE TITLE
ارتفاع فونت از پایین کم است و یک مشکل عجیب در نیم‌فاصله‌ی این فونت

### ISSUE THREAD

**Issue by Qaher-Marufiazar** [rastikerdar/vazir-code-font#15]
سلام. این گیف رو آماده کردم تا دقیقا مشکل ارتفاع فونت و نیز مشکل عجیب در نیم‌فاصله‌ش رو نشون بدم.

![gif2](https://user-images.githubusercontent.com/42169590/43795811-b56681b4-9a97-11e8-91ba-a5344b4fe24c.gif)

همانطوری که توی گیف می‌بینید فونت وزیر کد نسخه‌ی 1.0.3 فاصله‌ش از پایین، یعنی
win descent
منفی 190 هستش که با تست و تجربه حس می‌کنم منفی 220 قابل قبول باشه و حروفی مانند « ع » « می » چـ و غیره توی اکثر ویرایشگرها به درستی نشان داده خواهند شد.

مشکل دوم مربوط به کاراکتر نیم‌فاصله هستش! اونجا توی گیف شما وقتی یدونه نیم‌فاصله تایپ می‌کنی، کل کلمه رو به سمت راست می‌بره (البته میدونم یه سری مشکل و خطا از این ویرایشگری هستش که استفاده می‌کنم) با این وجود همین ویرایشگر خطای فونت رو هم لو داد. متوجه شدم شما اندازه عرض این کاراکتر نیم‌فاصله رو 500 قرار دادی (مثل بقیه‌ی گلیف‌ها). و وقتی از عرض 500 به 0 تبدیلش می‌کنی، مشکل دوم این گیف (حتی توی این ویرایشگر هم) رفع میشه.  همین ویرایشگر فونت تاهوما رو که میذاری عالی بدون هیچ مشکلی نشون میده. توصیه می‌کنم یه نگاه به گلیف‌های فونت تاهوما بندازید. واقعا فونت فوق العاده‌ای هستش این فونت تاهوما براش خیلی زحمت کشیدن! به نظرم عینا از این فونت تاهوما ایده بگیرید و نواقص این فونت وزیر رو مطابق با اون رفع بکنید.

من نمیدونم دقیقا شما این فونت رو با چه نر‌م‌افزاری درست کردید ولی ظاهرا هنگام خروجی گرفتن (احتمالا به خاطر نرم‌افزاری که استفاده می‌کنم) یه سری تغییرات ساده باعث میشه فونت بهم بریزه! 

به هر حال این دو تا مشکل رو حتما برای سری‌های بعدی رفع بکنید. انصافا فونت قشنگی هستش.

**Comment by rastikerdar** [comment]
سلام.
درست می‌فرمایید. اگرچه در تمام ادیتورهای سیستم من همه گلیف‌ها بدون مشکل قابل مشاهده است اما این‌جا ما با یک چالش جدی روبرو هستیم. فونت وزیرکد در واقع به فونت اینکانسولاتا اضافه شده. یعنی بنای اولیه بر این بود که متریک‌های فونت لاتین دست نخورده باقی بماند و تنها فارسی به آن اضافه شود. چون اگر مثلا عدد ۱۹۰ به ۲۲۰ تغییر کند فاصله خطوط در ادیتور یا هر جای دیگری زیادتر می‌شود. نمی‌دونم چاره کار چیست. این اندازه را تغییر داد یا دو تا نسخه کنار هم قرار داد یا ...

**Comment by Qaher-Marufiazar** [comment]
من تست کردم اگه نرم‌افزار ویرایشگر فونتی که استفاده می‌کنید کارش درست باشه با تغییر این اندازه به 220 مشکلی پیش نمیاد. فونت لاتین اینکانسولیتا فونت خوبیه ولی اگه بتونید وقت بذارید دو نسخه‌ی متفاوت و اما درست از وزیر کد بدید بیرون یکی با همین فونت لاتین و دیگری یا با کانسولاس یا فونت هک. طبق تجربه‌ی برنامه‌نویسی با اینکه کانسولاس یک فونت رایگان نیست ولی برای برنامه‌نویسی واقعا عالیست. یا می‌تونید از فونت‌های رایگانی چون فونت « هک » یا فونت مشابه کانسولاس مثل دروید مونو (مجوز آپاچی داره) استفاده بکنید. (در مورد انتخاب فونت لاتین مناسب در بخش مربوطه بحث خواهد شد)

چاره راحته. فونت‌های چندزبانه بایستی هم فارسی هم انگلیسش درست و درمون دیده بشن. شما از فونت تاهوما الگو بگیرید. به هر حال این فاصله‌ از پایین برای بخش فارسی باید درست بشه و حداقل به بخش مینیمم عمیقترین کاراکتر بچسبه تا اینکه مشکلی شبیه به تایپ « می » « ع » و غیره در غالب ویرایشگرها پیش نیاد.

**Comment by zoghal** [comment]
@Qaher-Marufiazar  میشود بفرمایید در چه ادیتوری با این مشکل برخوردید؟

**Comment by ijz1361** [comment]
<div dir=rtl>
سلام
کاش فرصت میشد برای این موضوع یک آپدیت منتشر می کردید برای مثال در  خانواده jetbrain مانند phpstorm, webstorm, pycharm و... این مسئله کمی آزاردهنده هست.
</div>

**Comment by sajaddp** [comment]
<div dir=rtl>سلام</div>
<div dir=rtl>
کاش فرصت میشد برای این موضوع یک آپدیت منتشر می کردید برای مثال در خانواده jetbrain مانند phpstorm, webstorm, pycharm و... این مسئله کمی آزاردهنده هست.
</div>

**Comment by rastikerdar** [comment]
در نسخه جدید هم مشکل نیم‌فاصله رفع شد و هم نسخه با ارتفاع بیشتر اضافه شد.
[rastikerdar.github.io/vazir-code-font/](https://rastikerdar.github.io/vazir-code-font/)
با تشکر

**Comment by bateni** [comment]
‫آیا در نسخهٔ ExtraHeight متریک ارتفاع قلم را افزایش داده‌ای؟
مشکلی که من در ویرایشگر می‌بینم این است که پس از تایپ علائمی مثل تنوین یا فتحه روی الف، یک‌هو ارتفاع خط زیاد می‌شه و یکنواخت بودن فاصله خطوط از بین می‌ره.

![image](https://user-images.githubusercontent.com/6666981/56078822-57cf1480-5dba-11e9-89b3-029de35f34a9.png)


یک راه‌حل این است که ارتفاع گلیف‌ها را به اندازه بلندترین کاراکتر تعیین کنی.  آن موقع، حس فضای خالی در متن به وجود میاد، اما لااقل فاصله خطوط یکنواخت می‌شه و با تغییر متن، بالا و پایین نمی‌پره :D

**Comment by rastikerdar** [comment]
همینطوره. متریک زیاد شده. توی چه برنامه‌ای به این مشکل برخوردین؟

**Comment by bateni** [comment]
‫با Emacs توی محیط Gnome در سیستم عامل Manjaro که مبتنی بر Arch Linux است.

‫جالب است که در برنامهٔ Gedit مشکل به شکل دیگری بروز می‌کند.

![image](https://user-images.githubusercontent.com/6666981/56083692-8ec31b80-5df6-11e9-85b7-20c12c6a0dfc.png)


‫اول کار تنوین در سطر دوم دیده نمی‌شود و همین‌که با استفاده از Alt-Tab به پنجرهٔ دیگری می‌روم، تنوین ظاهر می‌شود.

**Comment by bateni** [comment]
‫با Emacs توی محیط Gnome در سیستم عامل Manjaro که مبتنی بر Arch Linux است.

‫جالب است که در برنامهٔ Gedit مشکل به شکل دیگری بروز می‌کند.

‫اول کار تنوین در سطر دوم دیده نمی‌شود و همین‌که با استفاده از Alt-Tab به
پنجرهٔ دیگری می‌روم، تنوین ظاهر می‌شود.

**Comment by bateni** [comment]
فایل درست بارگزاری نمی‌شود:

[Animated version](http://mhbateni.com/img/peek-2019-04-13-14-09.gif)

**Comment by rastikerdar** [comment]
عذرخواهی می‌کنم. من اشتباه کرده بودم در متریک‌ها. توی نسخه جدید ارتفاع رو زیاد کردم. اگر فکر می‌کنید کم هست باز هم بیشترش کنم.
[github.com/rastikerdar/vazir-code-font/releases/latest](https://github.com/rastikerdar/vazir-code-font/releases/latest)

**Comment by bateni** [comment]
ممنونم، صابر، که این‌قدر سریع ترتیب اثر دادی.

خیلی عالی شده.  هنوز یک مقدار اندک تغییر ارتفاع دیده می‌شه.  نه برای آ یا
اَ؛ بلکه فقط برای تنوین: ثانیاً.

[animated](mhbateni.com/img/Peek-2019-04-13-15-42.gif)
