### ISSUE TITLE
آیا بهتر نیست این فونت شبیه فونت «وزیر» باشد؟

### ISSUE THREAD

**Issue by ali-hardan** [rastikerdar/vazir-code-font#16]
<div dir="rtl">
سلام و درود و تشکر بابت فونت فوق‌العاده زیبا و خوانای وزیر.

معمولا فونت‌های Monospace از نسخه‌ی معمولیشون خوانایی و وضوح بیشتری دارند؛ اصلا -اگه اشتباه نکنم- غایت فونت‌های Monospace این هست که وضوح و خوانایی بیشتری داشته باشن و آدم بتونه ساعت‌ها روی نوشتن متن تمرکز کنه.

فونت‌هایی مثل DejaVu Sans و DejaVu Sans Mono رو مقایسه کنید. می‌بینید که در نسخه Mono، وضوح و خوانایی بیشتر شده.

اما بعد از مقایسه فونت Vazir Code با Vazir، متوجه شدم خوانایی و زیبایی فونت نسبت به نسخه اصلی بسیار کاهش یافته و آدم رو ترغیب به نوشتن نمی‌کنه. من در حال حاضر، از فونت Vazir غیر Mono برای نوشتن متون فارسی استفاده می‌کنم.

لطفاً به من بگید، آیا توقع من اشتباهه؟ من توقع دارم فونت Vazir Code برای نوشتن مناسب‌تر باشه، ولی اینطور نیست.
</div>

**Comment by rastikerdar** [comment]
سلام
راستش من فکر می‌کنم اشتباهی رخ داده. فکر می‌کنم فلسفه اصلی فونت‌های مونواسپیس یکسان بودن عرض تمامی گلیف‌ها باشه نه خوانایی. توی لینک زیر شما می‌تونید سایر فونت‌های مونواسپیس عربی رو هم مشاهده بفرمایید.
IranOpenFontGroup/Discussions#7

نکته دیگر اینکه هم‌عرض بودن حروف در زبان لاتین امر ساده‌ایست اما در زبان فارسی به دلیلی پیوستگی و کشیدگی برخی حروف ماجرا کاملا متفاوت می‌شود. البته وزیرکد خیلی جای بهتر شدن داره اما خب ارزش وقت گذاشتن نداره.

در آخر اینکه پیشنهاد می‌کنم به قلم آذرمهرمونواسپیسد هم نگاهی بیندازید. کاری از 
@aminabedi68
[github.com/aminabedi68/AzarMehrMonospaced](https://github.com/aminabedi68/AzarMehrMonospaced)

**Comment by ali-hardan** [comment]
خیلی ممنونم. فهمیدم.
