### ISSUE TITLE
[Q] How to merge Vazir with different font?

### ISSUE THREAD

**Issue by dehghani-mehdi** [rastikerdar/vazir-code-font#18]
سلام،

1. آیا این کار از نظر شما مجاز هست؟
2. امکانش هست در خصوص نحوه کار راهنمایی کنید؟

ممنون

**Comment by rastikerdar** [comment]
سلام
۱. چرا که نه. با هر فونتی که بخواهید می‌تونید ترکیب کنید. وزیر برای هر نوع استفاده یا تغییری آزاد است.
۲. یک راه آن استفاده از برنامه‌ای مثل فونت‌فورج است. این نوع برنامه‌ها معمولا امکان ادغام فونت‌ها رو دارند.

**Comment by dehghani-mehdi** [comment]
ممنونم بابت پاسخ و اجازه

با برنامه فونت فورج آشنایی کمی دارم، در اصل تنها کاری که کردم تلفیق کاراکترهای لیگچر فونت فیرا کد با یک فونت مونو دیگه بوده (البته با کمک جامعه متن باز)، از قابلیت مرج خوده فونت فورج استفاده کردم، اما نتیجه ای حاصل نشد. خواستم بدونم شما از اسکریپت خاصی استفاده می کنید یا دستی باید این پروسه انجام بشه؟
و اینکه 32 حرف رو منتقل کنم کفایت میکنه؟

سپاس

**Comment by rastikerdar** [comment]
قاعدتا نباید مشکلی به جود بیاد چون اسکریپتی که من برای ساخت فونت‌ها استفاده می‌کنم دقیقا از مرج خود فونت‌فورج استفاده می‌کنه.  
[github.com/rastikerdar/fontbuilder](https://github.com/rastikerdar/fontbuilder)

**Comment by dehghani-mehdi** [comment]
فک میکنم این کار روی ویندوز قابل انجام نباشه، درسته؟

**Comment by rastikerdar** [comment]
اگر منظورتون خود اسکریپته که فکر نمی‌کنم. لااقل نه به راحتی.

**Comment by dehghani-mehdi** [comment]
آره، همچنین اون دیپندنسی هایی که ذکر کردید، قبلا دیده بودم و نتونستم راهی برای اجرا کردن همشون به صورت صحیح در ویندوز پیدا کنم.
ممنونم بابت وقتی که گذاشتید.
موفق باشید.

**Comment by dehghani-mehdi** [comment]
سلام مجدد،

آقا با همون امکانات فونت فورج فونت وزیر رو با فونت مدنظرم مرج کردم، اندازه کاراکترهای فارسی تقریبا 4 برابر کاراکترهای انگلیسی شد.
بعد همون روال رو با یک فونت فارسی دیگه انجام دادم اندازه ها مناسب بود.
می دونید که مشکل ممکنه از کجا ناشی شده باشه؟ و راه حل ش چیه؟

ممنون

**Comment by rastikerdar** [comment]
سلام
به منوی زیر برید
element->font info
قسمت
general-> Em size
رو در فونت مبدا و ادغامی چک کنید. توی مخزن دو تا سایز داریم. 1000 و 2048. هر کدام که به کارتان میاد استفاده کنید. اگر باز هم درست نشد گلیف‌های مورد نظر رو انتخاب کنید و تغییر سایز بدهید.

**Comment by dehghani-mehdi** [comment]
سلام،

هر دو کار رو قبل ارسال کامنت در اینجا انجام دادم. نتیجه ای حاصل نشد. ظاهرا فونت وزیر راضی به ادغام با اون یکی فونت نیست.
با اون یکی فونت کارم راه افتاد، چون نوع نوشتار وزیر رو دوست دارم، میخواستم اگر بشه از وزیر استفاده کنم.
اگر شد با لینوکس طبق راهنمایی بلی شما تست میکنم.

سپاس
