### ISSUE TITLE
غیرمهم اما شایان توجه

### ISSUE THREAD

**Issue by aziz** [rastikerdar/vazir-code-font#2]
<p dir="rtl" align="right">
نکته‌ای که به چشمم اومد اینه که تو مک این قلم تو دسته قلم‌های مونواسپیس یا به قول این برنامه قلم‌های مک، Fixed Width قرار نمیگیره!
یه چیزی باید توی تنظیمات یا متادیتای فونت جا افتاده باشه یا اشتباه باشه
</p>

**Comment by zoghal** [comment]
یحتمل اینه. نگاه کردم دیدم روی سنس سریف هست.
و فکر کنم برای همینه تو اتم هم کار نمیکنه. 
یکنفر تو توییتر بهم گفت.
![screenshot 2016-08-22 21 51 07](https://cloud.githubusercontent.com/assets/174688/17864578/dae2037c-68b3-11e6-8f68-d91f0861f13a.png)

**Comment by aziz** [comment]
در ۱.۰.۲ حل شد
