### ISSUE TITLE
درخواست بستهء مبتنی بر اِن پی اِم

### ISSUE THREAD

**Issue by PerseusTheGreat** [rastikerdar/vazir-code-font#20]
<div dir='rtl'>
درود.

سایت [unpkg](https://unpkg.com)، یک CDN رایگان است که تمامی بسته های مبتنی بر NPM را بدون معرفی مجدد و مستقیم از روی NPM سِرو مینماید.
در حال حاضر، قلم های [وزیر](https://unpkg.com/vazir-font@20.1.0/)، [شبنم](https://unpkg.com/shabnam-font@4.0.0/) و [صمیم](https://unpkg.com/samim-font@1.0.2/) از طریق unpkg در دسترس میباشند (روی اسامی قلم ها کلیک کنید)
لذا، خواهشمندم بستهء قلم های وزیر-کد، ساحل، گندم، تنها، ناهید و پرستو را نیز در NPM منتشر نمایید.
از این طریق، تمامی نسخه ها و ویراست های متفاوت هر قلم، به راحتی در اختیار استفاده کنندگان قرار خواهد گرفت.
پیشاپیش سپاسگزارم.
</div>

**Comment by rastikerdar** [comment]
سلام
به روی چشم. الان برای وزیرکد ساختم. فقط یه مشکلی وجود داره که مثلا همین پکیج صمیم یا شبنم توسط دیگران ساخته شده و من الان می‌بینم نسخه صمیم توی ان‌پی‌ام خیلی قدیمیه. 
یا باید به دوستان بگویم ادمین رو به من منتقل کنند یا اینکه پکیج‌های جدیدی با نامی غیر از نام اصلی منتشر کنم. نمی‌دونم درستش کدومه!

**Comment by PerseusTheGreat** [comment]
<div dir="rtl">
سپاس ویژه بابت این سرعت عمل!

فکر کنم هر دو راه حل رو میبایست امتحان بفرمایید.
بنده به شخصه، به عنوان یک کاربر استفاده کننده از قلم های زیبای شما، عجله ندارم.
شاید تنها حسن استفاده از unpkg برای کاربرانی چون بنده، دسترسی کامل به قلم ها، نسخه ها و ویراست ها، باشد؛ ولی با توجه به اینکه در ایران CDN مطلوبی با امکانات مشابه نداریم، اگر این مورد انجام شود، برای همه و حتی خود شما نیز مطلوب خواهد بود.
امیدوارم راه حل اول جواب دهد و نیاز به معرفی مجدد نباشد.
سپاس دو چندان.
</div>

**Comment by PerseusTheGreat** [comment]
<div dir="rtl">

جسارتا تقاضا دارم این مطلب را مطالعه فرموده و نظرتان را به بنده عنایت فرمایید:

[نحوه نگارش css جهت بارگذاری قلم در مرورگرهای نوین](https://gist.github.com/PerseusTheGreat/8c8e3a324cdf2e599542c95e2ac9d20c)


</div>

**Comment by rastikerdar** [comment]
تشکر می‌کنم برای نگارش این مطلب. حقیقتش نکته یا نظر خاصی به ذهنم نمی‌رسه. شفاف بود.

**Comment by PerseusTheGreat** [comment]
<div dir="rtl">

درود.
با توجه به انجام شدن مورد درخواست شده در رابطه با قلم وزیر-کد، ضمن عرض سپاس، معتقدم باز موندن این ایشیو از این پس بی مورده، بنابراین با اجازه تون این ایشیو رو می بندم.
البته همچنان منتظر بسته های ان پی ام برای قلم های دیگرتان هستم.
با آرزوی سلامتی و شادکامی.

</div>
