### ISSUE TITLE
مشکل ارتفاع فونت

### ISSUE THREAD

**Issue by Azoic** [rastikerdar/vazir-code-font#21]
فونت در نرم افزار پی‌اچ‌پی استورم بصورت برش خورده از پایین نشون داده میشه

![Untitled-1](https://user-images.githubusercontent.com/3455580/64003550-bacf0700-cb21-11e9-95c1-23b5076aafaa.jpg)
به حروف "ر ل ی ن و" در تصویر فوق دقت نمایید

**Comment by rastikerdar** [comment]
توی بسته فونت از نسخهٔ با ارتفاع بیشتر استفاده کنید.

**Comment by Azoic** [comment]
نسخه با ارتفاع بیشتر هم سایز فونت درشت تر هست و منی که فونت وزیر رو در کنار فونت کونزولاس استفاده میکنم همخوانی نداره

فونت consolas

![Untitled-1](https://user-images.githubusercontent.com/3455580/64076131-15a95f80-ccd6-11e9-86da-8f23d04903ee.jpg)
