### ISSUE TITLE
قرار دادن لینک حمایت مالی

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/vazir-code-font#3]
درود صابر جان چرا یکی در میون این بحث لینک حمایت مالی رو در صفحات پرزنت قرار میدی؟
اگر نیاز هست که برای هر قلم حتما یکی ایشو بزنه و بعد شما تمایل پیدا کنی به قرار دادن لینک. لطفا بگو تا من اینکار رو انجام بدم. :)

**Comment by rastikerdar** [comment]
آخه صالح جان وزیرکد یه چیزی برای کدنویس‌ها بود. کدنویس‌ها این جور چیزها رو زیاد با هم به اشتراک می گذارند.
اما گذشته از این خب صالح جان مگر گذاشتن لینک چه کمکی می کنه!

**Comment by zoghal** [comment]
صابر جان می‌دونم چی میگی، حق داری، شاید به طور کلی کمک نکنه، مخصوصا به شما.
اما راستش به من خیلی کمک می‌کنه. اگر توییتر من رو چک کنی همین دوستان برنامه نویس مون فعلا در نصایحی که به من می‌کنند این دو مورد رو ذکر می‌کنند:
۱- مثل مسلم تجاری کار کن حمایت می‌کنیم
۲- کار خوب رو صابر داره انجام میده مثل اون عمل کن

هرچند بارها متذکر شدم هدف فعالیت های من تولید انبوه فونت هست. نه یکی دوتا و برای رسیدن به این هدف باید بستر لازم ایجاد بشه. که مهمترینش فرهنگ سازی و اطلاع رسانی هست.
حالت اول مدت دوسال هست که در حال اجراست. همهٔ کسانی که استفاده می‌کنند راضی هستند. اما ایا پاسخ گوی نیاز ها هست؟ آیا توانسته جلوی طراحانی مثل طراح فونت روزنامه ایران رو بگیره؟  فکر کن دو روزنامه پرتیراژ رو گند زده به خطش  بعد میگه مردم باید چشمانشون عادت کنه :( درد داره خوب.
حالت دوم هم که دیگه خودت بهتر از هر کسی میدونی داستانش چیه. بچه خوب که هستی، ساکت و آرام که کار می‌کنی، از نظر اکثریت کار درست رو انجام که می‌دیدی. اما هر وقت صفحاتت فونت ها رو چک می‌کنم بازم دردم میاد که این ملت حرف تو خالی زن چرا آنقدر بدون تفکر حرف و فقط حرف می‌زنند.

اره عزیزم گذاشتن لینک دونیشن حداقل به من کمک می‌کنه که در پاسخ به این دوستان بگم راهکارهایی که ارائه می‌دید در قالب حرف زیبا و درست هست و در عمل پوچ و تهی هست.
حداقلش اینه فردا روزی که باز مشکل فونت و نبود تنوع پیش اومد و دیگر من و شما هم نیستیم.  این دوستان با نگاه کردن به همون صفحات  متوجه شوند که با به به گفتن فونت تولید نمیشه. شاید  آن لحظه اندکی تفکر عمیق در مورد رفتار و عملشون داشته باشند.

در کل  نزار بهونه‌ای برای اون دسته افراد که فقط حرف می‌زنند باقی بمونه.

----------
یک خواهش دقت کردم دیدم مبلق کلی دونیشن ها تو وزیر بروز نمیشه. تو ساحل هم دیده نمیشه. ایا دلیل خاصی داره؟ میشه خواهش کنم این مورد رو شفاف کنی و مبلغ دقیق رو نشون بدی؟!

**Comment by rastikerdar** [comment]
صالح جان. حساب توتیترت رو چک کردم راستش یه جورایی شوکه شدم!

قبل از هر چیز تبریک میگم تایپ فیس جدیدت رو. امیدوارم یه مشتری خوب براش پیدا بشه. البته یه نقد کوچولو به تایپ فیس هات دارم اینه که یه کم ناآشنا یا غیر رسمی هستند. هرچند که حرفه ای طراحی و پیاده شده اند. البته نیکا و فربد خیلی خوبن اما نمی دونم بازخوردها چجوری بوده. احساس می کنم یه نگاه خاصی به قلم داری. من خودم احتمالا نیاز به زمان بیشتری دارم تا چشمم به سبک و روشت عادت کنه. یا مثلا یادمه فونت بهدادت رو با پی فونت مقایسه کرده بودی که به نظر من اشتباه بود. من به شخصه بهداد رو به عنوان جایگزین پی فونت نمی تونم قبول کنم. پی فونت کاملا رسمی هست در صورتی که بهداد اینگونه نیست. سبکشون هم متفاوته. نه اینکه پی فونت رو بپسندم اما مقایسه اش هم با بهداد منطقی به نظرم نمی رسه. شاید با فربد یا نیکا بهتر باشه. منظورم اینه که نگاهت به مقوله تایپ فیس قلم یه کم برام عجیبه.

در مورد مسائل و حواشی:
۱. راستش نظر من هم اینه که مثل آقای ابراهیمی کار کنی. خودت هم که میگی همه راضی هستند و اشکالی هم نداره. چرا روش ایشون پاسخ گوی نیازها نباشه؟! شما دانش و مهارت خیلی خوبی در زمینه طراحی دارید.

۲. من خودم نمی دونم چه کار خاصی دارم انجام میدم که دوستان محبت دارند میگن درسته! حقیقتش من فقط چند تا تایپ فیس به ذهنم رسید که پیاده کردم. همین! اصلا کار دیگه ای هم انجام ندادم.

واقعیتش نمی دونم چرا این مسائل و بحث ها بین شما و دوستان پیش اومده. بیشتر فکر می کنم به نوعی سوءتفاهم هست. یعنی هم شما نیتتون خیره هم دوستان اما توی روش ها اتفاق نظر ندارید.

مبلغ دونیشن ها توی صفحات وزیر و ساحل به روز هست. همیشه به روز بوده. اگر زیاد نشده برای اینکه دونیتی نشده. البته پی پینگ مدتیه غیر فعال شده و معلوم نیست کی باز بشه اما خب من فکر نمی کنم دیگه اتفاق خاصی بیفته. یعنی بحث حمایت مالی یه جورایی به همین محدود میشه. ضمنا توی صفحه ساحل باید روی هر کدام از تصاویر کلیک کنی تا مبلغ رو ببینی. 

صالح جان! من نمی دونم چرا توی صفحات فونت هات حمایت مالی نمی بینم. یا اینکه از طرق دیگه ای حمایت شدی و میشی و تو این صفحات اضافه نمی کنی یا اینکه کسی تمایل به حمایت نداشته که این خودش یه علامت مهم می تونه باشه. چون به نظر من صالح جان حرف اول و آخر رو توی کارهات تایپ فیس میزنه. تایپ فیس اگر دلچسب و مقبول واقع بشه حتما حمایت میشه. مقبول واقعی! یعنی به طور جدی مورد استفاده قرار بگیره و یا اینکه به عنوان جایگزین فونت های قبلی قابل طرح باشه. با حرف و تمجید و ... چیزی روشن نمیشه. باید عملا ببینی دارن استفاده میکنن. یکی از دلایلی که من این فونت ها رو توسعه میدادم علاوه بر ایشوها و کامنت های وبلاگی و توییت ها، پیغام های خصوصی بسیاری بود که میگفتن این قابلیت رو هم بهش اضافه کن یا اینکه چجوری فلان جا استفاده کنم یا ایراداتش(قلم ها) رو متذکر می شدن یا پیشنهاد کمک میدادن و ...
توی ایشوها هم خودت میدیدی که همه چقدر خوب همکاری می کردند.

یعنی کارِت رو باید با مردم پیش ببری و دلگرم بشی.

به هر صورت پیشنهاد می کنم شما که می خوای کلا روی فونت فارسی متمرکز بشی به جای هدف مبهم تولید انبوه فونت، یک تایپ فیس خیلی خوب و تجاری طراحی یا بدون شبهه لایسنس ریدیزاین کنی بزاری برای فروش به شیوه آقای ابراهیمی یا کلا فروش امتیاز. اگر دیدی فروش نمیره پس در مورد شکل قلم و سلیقه مردم احتمالا باید تجدید نظر کنی.

**Comment by zoghal** [comment]
صابر جان از آنجا که دیگه می‌تونم بی چربی بی استخون راسه راسه و پوست کنده حرفام رو بزنم، و صحبت در مورد این سوالات هم با یک خط و دو خط جواب نمیده و بهتر از هر کسی با نقطه ضعف من که همون نگارش انشایی / املایی هست، به طور کلی قصد دارم سوالات رو کامل به صورت صوتی پاسخ بدم تا همه در جریان قرار بگیرند. یک faq صوتی از چهار سال :))

و از طرف دیگه این پروژه  [نون ](https://font-store.github.io/font-noon/)هم تقریبا الان تموم شد.  کلا خسته هستم . خواستم قبل از انجام این کار ازت بپرسم مشکلی نداری داری ، در چه حالتی نداری یا داری منظور همان مشکل روشی هست که می خوام انجام بدم. سوالات زیادی از دوستان بی پاسخ مونده.

**Comment by rastikerdar** [comment]
> خواستم قبل از انجام این کار ازت بپرسم مشکلی نداری داری ...

خیر! چه مشکلی؟! اگر فکر می کنی نامربوط بود یا حس خوبی در موردش نداری پاکش کنم. در مورد من هم هر گونه نقد یا ایرادی به روش یا قلم ها و ... داشتی بگو. هر چیزی که بهت کمک کنه.

پروژه نون هم پروژه واقعا بزرگ و مشکل و پرزحمتی هست. خسته نباشی. وقتی دیدم تعجب کردم. خدا قوت! دو تا ایشو خواستم برایش باز کنم اما تردید داشتم. چون در زمینه خط قرآنی و اقتضائاتش تخصصی ندارم. مثلا بحث تنوین‌ها یا ضخامت قلم.

موفق باشی

**Comment by rastikerdar** [comment]
صالح! من لیست حمایت های توی صفحه ساحل رو به صفحه وزیر اضافه کردم و مبلغ رو هم جمع زدم. اینطوری برای من هم بهتر شد.

ممنون

**Comment by zoghal** [comment]
> خیر! چه مشکلی؟! اگر فکر می کنی نامربوط بود یا حس خوبی در موردش نداری پاکش کنم. در مورد من هم هر گونه نقد یا ایرادی به روش یا قلم ها و ... داشتی بگو. هر چیزی که بهت کمک کنه.

نه بابا خیلی هم خوب بود. فقط چون سوالات بقیه هم تو همین مایه بود گفتم کلی پاسخ بدم که فعلا ۶ ساعته از زیر نون خارج شدم. و تازه می خوام به سایر کارها برسم.


> پروژه نون هم پروژه واقعا بزرگ و مشکل و پرزحمتی هست. خسته نباشی. وقتی دیدم تعجب کردم. خدا قوت! دو تا ایشو خواستم برایش باز کنم اما تردید داشتم. چون در زمینه خط قرآنی و اقتضائاتش تخصصی ندارم. مثلا بحث تنوین‌ها یا ضخامت قلم.

اخ اخ گفتی کردی حلاکم. بابا این قواعد تجوید و قراعت قران عجب داستان تخیلی واسه خودش داره. اصلا فکر نمی کردم. این همه پیچیدگی داشته باشه. روایت های محتلف، متن‌های مختلف که از نظر اعراب کلی متفاوت هستند.
مثلا دو نوع تنوین داریم یک تنوین معمولی یکی پله یا باز :)) سختیش اینه که یکی بهم میگه چی کار کنم من باید اجراش کنم. نکته خوبش اینکه که سعی کردم نون تموم حالات رو پشتیبانی کنه.
روی خود حروف هنوز کار نکردم. اصل حروف از یک فونت دیگه استخراج شده. و هماهنگی هاش رو خودم انجام دادم. و کلا خیلی مشکل داره. هرچیزی دیدی بگو میمونه تو ایشو برای پیگیری های بعدی.

**Comment by zoghal** [comment]
> صالح! من لیست حمایت های توی صفحه ساحل رو به صفحه وزیر اضافه کردم و مبلغ رو هم جمع زدم. اینطوری برای من هم بهتر شد.

خیلی مخلصیم که این آقا رو از اول اسم ما برداشتی. حال کردم اینجوری راحت ترم.

نمی دونم  از چه لحاظ بهتر شده برات اما برای من که مایه تاسف بود وقتی رقم  کلی رو دیدم. فکر میکردم تا الان مبلغی شده که بتونی یک مک بوکی بخری الان ....
دوسال پیش من بیش از این سر قضیه فونت وب حمایت گرفتم :(  روزگار دیگر مهربان نیست!!!!

بگذریم! اقا نمی‌دونم شما داستانت چیه و چه برنامه ای داری
اما من با توجه به این چیزی که دیدم، ادامه راه فونت آزاد بی فایده هست. حداقل برای من و تو این مرحله. همین ۶ تایپ فیس رو در یک وزن منتشر میکنم، اما در حد تیم ملی . دیگه ادامه شون نمیدم. چون این وضعیتی که دیدم و بازخوردی که از پی فونت گرفتم ارزش نداره بیش از این و تا همین جاش هم که ادامه دادم برای دینی بود که رو دوشم بود.

تصمیم دارم اینکار رو انجام بدم : 
 فونت ها رو تک وزن منتشر میکنم و توضیح میدم چرا  در شرایط فعلی نمی تونم به صورت آزاد توسعه اشون رو ادامه بدم  و ادامه توسعه به دو صورت امکان پذیر هست.

۱-۱- یا شخص دیگری پیدا میشود  و ادامه کار رو بر عهده می‌گیره.
۱-۲- یا برای ادامه هر تایپ فیس  نیاز هست ۱۵ میلیون سرمایه گزاری شود(این رقم برای جا انداختن قیمت طراحی حروف هست) . اگر هر فونت موفق شد ظرف ۵ ماه سرمایه گذاری لازم رو جذب کنه   سایر وزن‌ها رو منتشر می‌کنم. 
در غیر این صورت نسخه‌ای جدید با نام جدید ازش ایجاد می‌کنم و تجاریش میکنم.(چون تایپ فیس ها رو خودم طراحی کردم در مالکیت حقوقی خودم هست ).

نحوه سرمایه گذاری هم به این صورت هست که همون فرم دونیشن رو بدون پرداخت میزارم اگر هر فونت ۱٫۲ مبلغ رو جذب کرد تازه شروع به گرفتن پول ازشون می‌کنم. اینطوری نه دیگه من بدهکار کسی میشم.
نه عذر و بهانه‌ای برای کسی می‌مونه. 

حالا به نظرت در مورد این پلن چیه؟ پیشنهادی داری بدی بهم؟

**Comment by rastikerdar** [comment]
۱. خیلی خوشحال شدم که بالاخره صالح برگشت به ریل اصلی! حالا دیگه راحت میشه حرف زد.

۲.صد در صد موافقم که کلا به کار تجاری سوئیچ کنی. آنهم نه نصفه و نیمه بلکه حتی به صورت کامل. یه چیزی میگم بین خودمون باشه. اتفاقا کار تجاری کلاسش بیشتره و خواهان بیشتری داره. تو چشم ما ایرانی ها هر چیزی که ارزونتره حتما بی‌کیفیت تره. چه برسه به اینکه مفت باشه! دیگه حتما آشغاله!

۳.همه آدم‌ها تو دنیا از کمپانی‌های بزرگ گرفته تا خرده فروش‌ها همگی کار پولی می‌کنن بدون یه ذره تخفیف. اتفاقا مردم هم دوستشون دارند. خب چه اشکالی داره. هم به مردم خدمت می کنن هم به خودشون. مطمئن باش برد-برد هست.

۴.پول جمع کردن برای کارهای هنری بی فایده هست. درست هم نیست. مثل قضیه پی فونت که خروجیش مقبول نشد اگر چه حرفه ای هم کار شده باشه. چون موضوع بیشتر سلیقه ای و ذوقی هست تا علمی! این پولی هم که جمع شد جوگیری بود. خود من هم جوگیری پول دادم. حالا برای بار دوم مطمئن باش کسی حمایت نمی کنه. پول اگر بعد از انتشار تایپ فیس و با دل خوش و رضایت قلبی از تایپ فیس جمع بشه درسته، نه قبل از انتشار! که اونهم میشه همین کاری که من انجام دادم و مردم بعد از دیدن خروجی کمک کردند و نهایتا همین مقداری که دیدی پول جمع شد. فکر میکنی اگر فونت آقای ابراهیمی آزاد منتشر میشد مردم چقدر حمایت می کردند؟
باور کن این مربوط به مردم ما نمیشه. همه جا همینجوره. کارهای هنری همینه. خود من هم همینطوریم!

۵. من هیچ برنامه ای برای فونت ندارم. همین بود صالح عزیز.

۶. به نظر من فونت هات عملا منتشر شده و دیگه کار خاصی نمی خواد انجام بدی. شما تا الان خیلی خیلی بیشتر از دینی که داشتی ادا کردی که درواقع به نظر من اصلا دینی هم نداشتی. بیشتر ناشی از حس اشتباه تقدسی بود که به مقوله خط و فونت فارسی داده بودی در صورتی که این هم مثل همه ابزارهای دیگر زندگی است. هر کدام در جای خودشان کاربرد دارند. همین! اشتباه است کسی اونو به عنوان هویت خودش معرفی کنه. ارزش حقیقت وجودی آدمها با این چیزها نباید نازل بشه! باور کن اصلا بحث فونت فارسی نیاز به منجی نداره!

۷. از این به بعد سوئیچ کن رو کار تجاری. مهمترین مسئله پیدا کردن بازار فروش هست. توی مردم عادی و فالوئرها و ... دنبال مشتری نگردد. اونجا همه مثل هم هستیم. نه رئیس کمپانی بزرگ هستیم. نه پولدار. نه ... باید بری اونجایی که ده ها و صدها میلیون برای تایپ فیس پول و این چیزها و حتی چیزهای بی ارزش میدن. برای فروش نسخه ای هم اگر بخوای مثل آقای ابراهیمی عمل کنی یه نکته رو باید در نظر داشته باشی! فونت هات باید قابل رقابت چه با فونت های ایشون، چه با فونت های رایگان قدیم و چه این فونت های جدیدی که اخیرا منتشر شده باشه. یعنی اونقدر باید شاخ باشه که طرف بگه وای خدای من چه فونت فوق العاده ای و حاضر بشه از همه گزینه های موجود به ویژه فونت های دیگه پولی دل بکنه و برای فونت شما پولی بپردازه! از فکر ترحم یا دلسوزی مردم بیا بیرون!

۸. اگر می خوای دنبال سرمایه گزار بگردی دنبال دانه درشت هاش بگرد. از فکر دونیت و اینا هم بیا بیرون. صادقانه بگم ما مردم عادی دیگه پولی برای این جور کارها نداریم!

۹. مهمترین وزن همین وزن معمولی فونت هایت هست که منتشر کردی. در واقع شما کارت اصلیت رو مفت رو کردی! وزن های دیگر فونت اونقدر جذاب نیست که بتونه سرمایه آنهم در سطح مردمی جمع کنه!

۱۰. به فکر بحث آموزش، تالیف کتاب، فروش تجاری برنامه هایی که نوشتی و ... هم باش. از هر چیزی که امکانش هست درآمد ایجاد کن برای خودت. هم ما مردم سود می کنیم و هم خودت! همانطوری که همه طراحان تا الان تو زمینه خط فارسی سود کردند! کلی هم سود کردند و حتی یک نفر هم معترض نشده! چون عیبی هم نداره. مردم هم سود کرده اند. خط فارسی یک ابزار هست برای ارتباط. یک چیز هست! چیز! چیز به خودی خود ارزشی نداره صالح جان!

:)
