### ISSUE TITLE
مشکل در فاصله بین خطوط

### ISSUE THREAD

**Issue by a-font** [rastikerdar/vazir-code-font#9]
<div dir="rtl" style="text-align=right;">
با سلام
لطفاً بررسی کنید که علت نمایش این فونت در نوت‌پد به صورت زیر چیست؟

> هیچکدام از نودها پیاده سازی نشده است پیچ
</div>
<img src="https://cloud.githubusercontent.com/assets/25431434/22421895/7de70148-e6e1-11e6-9e17-338f8656e720.png" />
<div dir="rtl" style="text-align=right;">
همانطور که می‌بینید نقاط حرف پ و انتهای حرف چ و م نمایش داده نمی‌شود
لازم به ذکر است که مشکل یاد شده ربطی به اندازه فونت نداشته و در سایزهای بالاتر و یا پایین‌تر مشکل به همین صورت می‌باشد و این مشکل فقط مربوط به دو حرف یاد شده نیست بلکه حروف دیگری که بخشی از آنها در زیر خط کرسی قرار می‌گیرند را شامل می‌شود که احتمالاً با کمی بیشتر کردن فاصله بین خطوط مشکل رفع گردد
</div>

**Comment by rastikerdar** [comment]
با سلام و احترام
کاملا درست می‌فرمایید. مقدار فراز و فرود و همچنین متریک‌های فونت همان فونت لاتین می‌باشد. حقیقتش هدف اصلی من از این فونت برای کد نویسی بود برای همین سعی کردم با بقیه قلم‌های هم نوع نیز هماهنگ باشه. الان فکر می‌کنم توی اغلب ویرایشگرهای برنامه‌نویسی، قلم به درستی نمایش داده میشه. توی وورد هم که تست کردم درست بود. اما خب از نقطه نظر استاندارد آن چیزی که می‌فرمایید کاملا صحیح می‌باشد.
ای کاش در برنامه های دیگر هم تست می‌فرمودید ببینید این مشکل کماکان برقرار است یا خیر؟ چون شاید بشه از خیر نوت‌پد گذشت.

**Comment by a-font** [comment]
<div dir="rtl" style="text-align: right">
با سلام
مشکل یاد شده در برنامه ورد هم به همین صورت است، در صورتی که در سایر فونت‌ها این مشکل وجود ندارد
فاصله بین خطوط می‌بایست بر روی یک تنظیم شود
</div>
<img src="https://cloud.githubusercontent.com/assets/25431434/22438209/5683beac-e740-11e6-86f4-e3d07b0a44cc.png" />

**Comment by rastikerdar** [comment]
توی نسخه بعدی این مورد لحاظ میشه. البته فکر می‌کنم قبلش باید یه بررسی کنم که توی ادیتورهای مختلف در صورت افزایش فاصله چه اتفاقی می افته. هر چند که فونت کوکب مونو فاصله رو افزایش داده.
به هر صورت ممنونم برای گزارش این ایراد.

**Comment by h4iku** [comment]
توی TeXstudio هم من این مشکل رو دارم، علاوه بر نقطهٔ حروفی مثل پ و چ، علائم نگارشی مثل کسره هم دیده نمیشن. تاجایی که باهاش کلنجار رفتم با افزایش linespacing توی ادیتور هم قضیه درست نشد و صرفاً فقط فاصلهٔ بین خطوط بیشتر شد.
البته با این‌حال بازم اینقدر فونت خوب و دلنشینی هست که نمیشه ازش استفاده نکرد :)

**Comment by ars543210** [comment]
با سلام.
بنده هم این مشکل رو دیدم علاوه بر اون یک استفاده دیگه هم از این فونت میکنم. و اونم برای مطالعه متون فارسی روی دستگاه های کتابخوان آمازون کیندل هست که فقط فونت های مونو اسپیس رو ساپورت میکنه. برای من مساوی بودن ارتفاع خطوط مهم نیست و فقط اینکه حروف رو به خوبی نمایش بده مهم هست.

**Comment by rastikerdar** [comment]
سلام
درست می‌فرمایید.
یه نسخه موقت با متریک های جدید برای شما آماده کردم امتحان بفرمایید اگر مشکلی داشتید مرا در جریان بگذارید. برای بولد هم دوست دارم اما حقیقتش فرصت نمی‌کنم.

[Vazir-Code.ttf.zip](https://github.com/rastikerdar/vazir-code-font/files/923767/Vazir-Code.ttf.zip)

از @a-font  هم بابت طولانی شدن این ایشو عذرخواهی می‌کنم.

**Comment by zoghal** [comment]
@rastikerdar سال نو مبارک صابر جان، من هم تو نوت پد پلاس این مشکل رو چند روز پیش دیدم.
این نسخه که آماده کردی روی مخزن کامیت شده؟

**Comment by ars543210** [comment]
> سلام
> درست می‌فرمایید.
> یه نسخه موقت با متریک های جدید برای شما آماده کردم امتحان بفرمایید اگر مشکلی داشتید مرا در جریان بگذارید. برای بولد هم دوست دارم اما حقیقتش فرصت نمی‌کنم.
> 
> Vazir-Code.ttf.zip

دمت گرم عالیه 😍😘
همونیه که میخواستم.
بازم ممنون

**Comment by rastikerdar** [comment]
@zoghal متشکرم. سال نو شما هم مبارک باشد. خیر کامیت نکردم. البته همین فایل بالا کار رو راه میندازه. من فقط متریک‌هاشو تغییر دادم.

**Comment by rastikerdar** [comment]
در بسته جدید فونت، نسخه با ارتفاع بیشتر نیز قرار گرفت. با تشکر
[rastikerdar.github.io/vazir-code-font/](https://rastikerdar.github.io/vazir-code-font/)
